fix cq_name, fix tests

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -59,29 +59,29 @@ script:
   # TEST = basic
   - >
     if [ "$TEST" = "basic" ]; then
-    result=$(curl http://localhost:8086/query?db=$db_name --data-urlencode "q=SHOW RETENTION POLICIES" | jq .results[0].series[0].values[0][0]);
-    [ "$result" != "$rp_name" ]
-    && (echo -e "Retention policy test: fail ('$result' != '$rp_name')"; exit 1)
-    || (echo "Retention policy test: pass"; exit 0);
+    result=$(curl http://localhost:8086/query?db=$db_name --data-urlencode "q=SHOW RETENTION POLICIES" | jq .results[0].series[0].values[1][0]);
+    [ "$result" = "$rp_name" ]
+    && (echo "Retention policy test: pass"; exit 0)
+    || (echo -e "Retention policy test: fail ('$result' != '$rp_name')"; exit 1);
     fi
 
   # TEST = setup
   - >
     if [ "$TEST" = "setup" ]; then
     result=$(curl http://localhost:8086/query?db=$db_name --data-urlencode "q=SELECT MEAN(usage_user) AS usage_user FROM $db_name.$rp_name.cpu WHERE time >= now() -1m" | jq .results[0].series[0].values[0][1])
-    [ -z "$result" ]
-    && (echo -e "Setup test: fail ($result)"; exit 1)
-    || (echo "Setup test: pass"; exit 0);
+    [ "$result" -gt 0 ]
+    && (echo "Setup test: pass"; exit 0)
+    || (echo -e "Setup test: fail ($result)"; exit 1);
     fi
 
   # TEST = migration
   - >
     if [ "$TEST" = "migration" ]; then
     curl -s http://localhost:8086/query?db=$db_name --data-urlencode "q=SELECT * FROM $db_name.$rp_name.test";
-    result=$(curl -s http://localhost:8086/query?db=$db_name--data-urlencode "q=SELECT * FROM $db_name.$rp_name.test" | jq .results[0].series[0].values[0][1]);
-    [ "$result" -ne 35 ]
-    && (echo "Aggregation test failed: ('$result' != 35)"; exit 1)
-    || (echo "Aggregation test: pass"; exit 0);
+    result=$(curl -s http://localhost:8086/query?db=$db_name --data-urlencode "q=SELECT * FROM $db_name.$rp_name.test" | jq .results[0].series[0].values[0][1]);
+    [ "$result" = "35" ]
+    && (echo "Aggregation test: pass"; exit 0)
+    || (echo "Aggregation test failed: ('$result' != 35)"; exit 1);
     fi
 
   # TEST = compact
@@ -91,13 +91,13 @@ script:
     curl -s http://localhost:8086/query?db=$db_name --data-urlencode "q=SELECT MEAN(usage_user) AS usage_user FROM $db_name.$rp_name.cpu";
     result1=$(curl -s http://localhost:8086/query?db=$db_name --data-urlencode "q=SELECT MEAN(usage_user) AS usage_user FROM $db_name.$rp_name.cpu" | jq .results[0].series[0].values[0][1]);
     result2=$(curl -s http://localhost:8086/query?db=$db_name --data-urlencode "q=SELECT MEAN(usage_user) AS usage_user FROM $db_name..cpu" | jq .results[0].series[0].values[0][1]);
-    [ "$result1" != "$result2" ]
-    && (echo -e "Compact test: fail (new RP is not default):\n$result1 != $result2"; exit 1)
-    || (echo "Compact test: pass (new RP is default)"; exit 0);
+    [ "$result1" = "$result2" ]
+    && (echo "Compact test: pass (new RP is default)"; exit 0)
+    || (echo -e "Compact test: fail (new RP is not default):\n$result1 != $result2"; exit 1);
     result3=$(curl -s http://localhost:8086/query?db=$db_name --data-urlencode "q=SELECT MEAN(usage_user) AS usage_user FROM $db_name.autogen.cpu" | jq .results[0].error);
-    [ -z "$result3" ]
-    && (echo "Compact test: fail (source still exists)"; exit 1)
-    || (echo "Compact test: pass (source is gone)"; exit 0);
+    [ -n "$result3" ]
+    && (echo "Compact test: pass (source is gone)"; exit 0)
+    || (echo "Compact test: fail (source still exists)"; exit 1);
     fi
 
 after_script:
