add test "setup" and some cleanup

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -12,6 +12,7 @@ env:
   global:
   matrix:
     - TEST=basic db_name=telegraf rp_name=rp_4d
+    - TEST=setup db_name=telegraf_30d rp_name=rp_30d
     - TEST=migration db_name=test_4d rp_name=rp_4d db_name_source=test
     - TEST=compact db_name=telegraf rp_name=rp_4d
 
@@ -29,10 +30,16 @@ install:
   - docker run -d --name influxdb -p 8086:8086 -v $PWD/integration/influxdb:/var/lib/influxdb influxdb:alpine
 
   # start telegraf to continuously write data to influxdb
-  - if [ "$TEST" = "compact" ]; then docker run -d --net host --name telegraf telegraf:alpine; sleep 10; fi
+  - >
+    if [ "$TEST" = "setup" -o "$TEST" = "compact" ]; then
+    docker run -d --net host --name telegraf telegraf:alpine; sleep 10;
+    fi
 
   # Seed influxdb
-  - if [ "$TEST" = "migration" ]; then ./tests/seed.sh 1m 10s "$(date -d -1hour +"%Y-%m-%d %H:%M:00")" seq+step10; fi
+  - >
+    if [ "$TEST" = "migration" ]; then
+    ./tests/seed.sh 1m 10s "$(date -d -1hour +"%Y-%m-%d %H:%M:00")" seq+step10;
+    fi
 
 script:
   # Check the role/playbook's syntax.
@@ -51,10 +58,19 @@ script:
   # TEST = basic
   - >
     if [ "$TEST" = "basic" ]; then
-    result=$(curl http://localhost:8086/query?db=telegraf --data-urlencode "q=SHOW RETENTION POLICIES" | jq .results[0].series[0].values[0][0]);
+    result=$(curl http://localhost:8086/query?db=$db_name --data-urlencode "q=SHOW RETENTION POLICIES" | jq .results[0].series[0].values[0][0]);
     [ "$result" != "$rp_name" ]
-    && (echo -e "Retention policy test: fail\n$result"; exit 1)
+    && (echo -e "Retention policy test: fail ('$result' != '$rp_name')"; exit 1)
     || (echo "Retention policy test: pass"; exit 0);
+    fi
+
+  # TEST = setup
+  - >
+    if [ "$TEST" = "setup" ]; then
+    result=$(curl http://localhost:8086/query?db=$db_name --data-urlencode "q=SELECT MEAN(usage_user) AS usage_user FROM $db_name.$rp_name.cpu WHERE time >= now() -1m" | jq .results[0].series[0].values[0][1])
+    [ -z "$result" ]
+    && (echo -e "Setup test: fail ($result)"; exit 1)
+    || (echo "Setup test: pass"; exit 0);
     fi
 
   # TEST = migration
@@ -62,22 +78,24 @@ script:
     if [ "$TEST" = "migration" ]; then
     curl -s http://localhost:8086/query?db=$db_name --data-urlencode "q=SELECT * FROM $db_name.$rp_name.test";
     result=$(curl -s http://localhost:8086/query?db=$db_name--data-urlencode "q=SELECT * FROM $db_name.$rp_name.test" | jq .results[0].series[0].values[0][1]);
-    [ "$result" -ne 35 ] && (echo "Aggregation test failed: '$result' != 35"; exit 1) || (echo "Aggregation test: pass"; exit 0);
+    [ "$result" -ne 35 ]
+    && (echo "Aggregation test failed: ('$result' != 35)"; exit 1)
+    || (echo "Aggregation test: pass"; exit 0);
     fi
 
   # TEST = compact
   - >
     if [ "$TEST" = "compact" ]; then
-    curl -s http://localhost:8086/query?db=telegraf --data-urlencode "q=SELECT MEAN(usage_user) AS usage_user FROM telegraf.autogen.cpu";
-    curl -s http://localhost:8086/query?db=telegraf --data-urlencode "q=SELECT MEAN(usage_user) AS usage_user FROM telegraf.$rp_name.cpu";
-    result1=$(curl -s http://localhost:8086/query?db=telegraf --data-urlencode "q=SELECT MEAN(usage_user) AS usage_user FROM telegraf.$rp_name.cpu" | jq .results[0].series[0].values[0][1]);
-    result2=$(curl -s http://localhost:8086/query?db=telegraf --data-urlencode "q=SELECT MEAN(usage_user) AS usage_user FROM telegraf..cpu" | jq .results[0].series[0].values[0][1]);
+    curl -s http://localhost:8086/query?db=$db_name --data-urlencode "q=SELECT MEAN(usage_user) AS usage_user FROM $db_name.autogen.cpu";
+    curl -s http://localhost:8086/query?db=$db_name --data-urlencode "q=SELECT MEAN(usage_user) AS usage_user FROM $db_name.$rp_name.cpu";
+    result1=$(curl -s http://localhost:8086/query?db=$db_name --data-urlencode "q=SELECT MEAN(usage_user) AS usage_user FROM $db_name.$rp_name.cpu" | jq .results[0].series[0].values[0][1]);
+    result2=$(curl -s http://localhost:8086/query?db=$db_name --data-urlencode "q=SELECT MEAN(usage_user) AS usage_user FROM $db_name..cpu" | jq .results[0].series[0].values[0][1]);
     [ "$result1" != "$result2" ]
     && (echo -e "Compact test: fail (new RP is not default):\n$result1 != $result2"; exit 1)
     || (echo "Compact test: pass (new RP is default)"; exit 0);
-    result3=$(curl -s http://localhost:8086/query?db=telegraf --data-urlencode "q=SELECT * FROM telegraf.autogen.cpu" | jq .results[0].error);
+    result3=$(curl -s http://localhost:8086/query?db=$db_name --data-urlencode "q=SELECT MEAN(usage_user) AS usage_user FROM $db_name.autogen.cpu" | jq .results[0].error);
     [ -z "$result3" ]
-    && (echo -e "Compact test: fail (source still exists:\n$result3)"; exit 1)
+    && (echo "Compact test: fail (source still exists)"; exit 1)
     || (echo "Compact test: pass (source is gone)"; exit 0);
     fi
 
