use if..then

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -14,9 +14,13 @@ env:
 before_install:
   # Make sure everything's up to date.
   - >
-    [ "$TEST" = "basic" ] && "sudo apt-get update -qq"
+    if [ "$TEST" = "basic" ]; then 
+      sudo apt-get update -qq
+    fi
   - >
-    [ "$TEST" = "basic" ] && "docker run -d --name influxdb -p 8086:8086 -v $PWD/integration/influxdb:/var/lib/influxdb influxdb:alpine"
+    if [ "$TEST" = "basic" ]; then 
+      docker run -d --name influxdb -p 8086:8086 -v $PWD/integration/influxdb:/var/lib/influxdb influxdb:alpine
+    fi
 
 install:
   # Install Ansible.
@@ -29,23 +33,23 @@ script:
   # TEST = basic
   # Check the role/playbook's syntax.
   - >
-    [ "$TEST" = "basic" ] && "ansible-playbook -i tests/inventory tests/test.yml --syntax-check"
+    if [ "$TEST" = "basic" ]; then ansible-playbook -i tests/inventory tests/test.yml --syntax-check; fi
   # Run the role/playbook with ansible-playbook.
   - >
-    [ "$TEST" = "basic" ] && "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo"
+    if [ "$TEST" = "basic" ]; then ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo; fi
 
   # Run the role/playbook again, checking to make sure it's idempotent.
   - >
-    [ "$TEST" = "basic" ] && { 
-    ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
-    | grep -q 'changed=0.*failed=0'
-    && (echo 'Idempotence test: pass' && exit 0)
-    || (echo 'Idempotence test: fail' && exit 1) 
-    }
+    if [ "$TEST" = "basic" ]; then 
+      ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
+      | grep -q 'changed=0.*failed=0'
+      && (echo 'Idempotence test: pass' && exit 0)
+      || (echo 'Idempotence test: fail' && exit 1) 
+    fi 
 
   # TEST = migration
   - >
-    [ "$TEST" = "migration" ] && "echo 'success'"
+    if [ "$TEST" = "migration" ]; then echo 'success'; fi
 
 after_script:
   - curl http://localhost:8086/query?db=telegraf --data-urlencode "q=SHOW DATABASES"
