add colors to test results

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -10,6 +10,9 @@ dist: xenial
 
 env:
   global:
+    - GREEN='\033[0;32m'
+    - RED='\033[0;31m'
+    - NC='\033[0m' # No Color
   matrix:
     - TEST=basic db_name=telegraf rp_name=rp_4d
     - TEST=setup db_name=telegraf_30d rp_name=rp_30d
@@ -54,8 +57,8 @@ script:
   - >
     yes | ansible-playbook -i tests/inventory tests/test.yml --connection=local
     | grep -q 'changed=0.*failed=0'
-    && (echo 'Idempotence test: pass' && exit 0)
-    || (echo 'Idempotence test: fail' && exit 1);
+    && (echo -e 'Idempotence test: ${GREEN}pass${NC}' && exit 0)
+    || (echo -e 'Idempotence test: ${RED}fail${NC}' && exit 1);
 
   # TEST = basic
   - >
@@ -63,8 +66,8 @@ script:
     result=$(curl http://localhost:8086/query?db=$db_name --data-urlencode 
     "q=SHOW RETENTION POLICIES" | jq .results[0].series[0].values[1][0] |tr -d '"');
     [ "$result" = "$rp_name" ]
-    && (echo "Retention policy test: pass"; exit 0)
-    || (echo -e "Retention policy test: fail ('$result' != '$rp_name')"; exit 1);
+    && (echo -e "Retention policy test: ${GREEN}pass${NC}"; exit 0)
+    || (echo -e -e "Retention policy test: ${RED}fail${NC} ('$result' != '$rp_name')"; exit 1);
     fi
 
   # TEST = setup (wait for CQ to run)
@@ -77,8 +80,8 @@ script:
     "q=SELECT ROUND(MEAN(usage_user)) AS usage_user FROM $db_name.$rp_name.cpu WHERE time >= now() -1m" 
     | jq .results[0].series[0].values[0][1]);
     [ "$result" -gt 0 ]
-    && (echo "Setup test: pass"; exit 0)
-    || (echo -e "Setup test: fail ($result)"; exit 1);
+    && (echo -e "Setup test: ${GREEN}pass${NC}"; exit 0)
+    || (echo -e -e "Setup test: ${RED}fail${NC} ($result)"; exit 1);
     fi
 
   # TEST = migrate
@@ -88,8 +91,8 @@ script:
     result=$(curl -s http://localhost:8086/query?db=$db_name --data-urlencode 
     "q=SELECT * FROM $db_name.$rp_name.test" | jq .results[0].series[0].values[0][1]);
     [ "$result" = "35" ]
-    && (echo "Aggregation test: pass"; exit 0)
-    || (echo "Aggregation test failed: ('$result' != 35)"; exit 1);
+    && (echo -e "Aggregation test: ${GREEN}pass${NC}"; exit 0)
+    || (echo -e "Aggregation test ${RED}fail${NC}ed: ('$result' != 35)"; exit 1);
     curl -s http://localhost:8086/query?db=$db_name --data-urlencode
     "q=SHOW CONTINUOUS QUERIES" | jq . | grep 'cq_cpu_';
     sed -i -e 's#^\( *interval: "\)1m\(".*\)$#\130s\2#' -e 's#^\(.*every: "\)1m\(".*\)$#\130s\2#' ./tests/vars/migrate.yml;
@@ -100,11 +103,11 @@ script:
     result1="$(echo "$result" | grep "_30s")";
     result2="$(echo "$result" | grep "_1m")";
     [ -n "$result1" ] 
-    && (echo "CQ update test: pass (new CQ exists)"; exit 0)
-    || (echo "CQ update test: fail (new CQ does not exist)"; exit 1);
+    && (echo -e "CQ update test: ${GREEN}pass${NC} (new CQ exists)"; exit 0)
+    || (echo -e "CQ update test: ${RED}fail${NC} (new CQ does not exist)"; exit 1);
     [ -z "$result2" ] 
-    && (echo "CQ update test: pass (old CQ is gone)"; exit 0)
-    || (echo "CQ update test: fail (old CQ still exists = $result2)"; exit 1); 
+    && (echo -e "CQ update test: ${GREEN}pass${NC} (old CQ is gone)"; exit 0)
+    || (echo -e "CQ update test: ${RED}fail${NC} (old CQ still exists = $result2)"; exit 1); 
     fi
 
   # TEST = compact
@@ -119,13 +122,13 @@ script:
     result2=$(curl -s http://localhost:8086/query?db=$db_name --data-urlencode 
     "q=SELECT MEAN(usage_user) AS usage_user FROM $db_name..cpu" | jq .results[0].series[0].values[0][1]);
     [ "$result1" = "$result2" ]
-    && (echo "Compact test: pass (new RP is default)"; exit 0)
-    || (echo -e "Compact test: fail (new RP is not default):\n$result1 != $result2"; exit 1);
+    && (echo -e "Compact test: ${GREEN}pass${NC} (new RP is default)"; exit 0)
+    || (echo -e -e "Compact test: ${RED}fail${NC} (new RP is not default):\n$result1 != $result2"; exit 1);
     result3=$(curl -s http://localhost:8086/query?db=$db_name --data-urlencode 
     "q=SELECT MEAN(usage_user) AS usage_user FROM $db_name.autogen.cpu" | jq .results[0].error);
     [ -n "$result3" ]
-    && (echo "Compact test: pass (source is gone)"; exit 0)
-    || (echo "Compact test: fail (source still exists)"; exit 1);
+    && (echo -e "Compact test: ${GREEN}pass${NC} (source is gone)"; exit 0)
+    || (echo -e "Compact test: ${RED}fail${NC} (source still exists)"; exit 1);
     fi
 
   - >
