fix again...

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -41,10 +41,10 @@ script:
   # Run the role/playbook again, checking to make sure it's idempotent.
   - >
     if [ "$TEST" = "basic" ]; then 
-      ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
-      | grep -q 'changed=0.*failed=0'
-      && (echo 'Idempotence test: pass' && exit 0)
-      || (echo 'Idempotence test: fail' && exit 1) 
+    ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo 
+    | grep -q 'changed=0.*failed=0'
+    && (echo 'Idempotence test: pass' && exit 0)
+    || (echo 'Idempotence test: fail' && exit 1);
     fi 
 
   # TEST = migration
