use full db name everywhere, fix migration test

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -25,7 +25,7 @@ install:
   - printf "[defaults]\nroles_path = ../" > ansible.cfg
 
   # Seed influxdb
-  - if [ "$TEST" = "migration" ]; then ./tests/seed.sh 1m 10s "2018-09-05 08:00:00" seq+step10; fi
+  - if [ "$TEST" = "migration" ]; then ./tests/seed.sh 1m 10s "$(date -d -1hour +"%Y-%m-%d %H:%M:00")" seq+step10; fi
 
 script:
   # Check the role/playbook's syntax.
@@ -45,7 +45,7 @@ script:
     if [ "$TEST" = "migration" ]; then 
     curl -s http://localhost:8086/query?db=test_agg --data-urlencode "q=SELECT * FROM test_agg.rp_7d.test";
     result=$(curl -s http://localhost:8086/query?db=test_agg --data-urlencode "q=SELECT MEAN(value) FROM test_agg.rp_7d.test" | jq .results[0].series[0].values[0][1]); 
-    [ "$result" -ne 35 ] && (echo "'$result' != 35"; exit 1);
+    [ "$result" -ne 35 ] && (echo "Aggregation test failed: '$result' != 35"; exit 1) || (echo "Aggregation test: pass"; exit 0);
     fi
 
 after_script:
